repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.11.0  # Use the version compatible with your project
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ['--ignore=E501,B008,E203']

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest version
    hooks:
      - id: isort
        language_version: python3.10

  # Add other hooks here as needed
